const data = {
  imageDetails: [
    {
      name: 'Hafiz & Nik',
      images: 'images/img5.jpeg',
      slug: 'hafiz-nik',
      desc: "Congratulations to Hazim and Sya on their special day! 🎉 May your love continue to grow stronger with each passing day, and may your journey together be filled with laughter, love, and endless joy. Here's to a lifetime of happiness and beautiful moments together. Cheers to the newlyweds! ",
    },
    {
      name: 'Syaz & Izat',
      images: '/images/DSC_3723.jpg',
      slug: 'syaz-izzat',
      desc: "Congratulations to Hazim and Sya on their special day! 🎉 May your love continue to grow stronger with each passing day, and may your journey together be filled with laughter, love, and endless joy. Here's to a lifetime of happiness and beautiful moments together. Cheers to the newlyweds! ",
      moreImages: [
        '/images/Hazim-Sya/DSC02934.jpg',
        '/images/Hazim-Sya/DSC02987.jpg',
        '/images/Hazim-Sya/DSC03066.jpg',
        '/images/Hazim-Sya/DSC03425.jpg',
        '/images/Hazim-Sya/DSC03443.jpg',
        '/images/Hazim-Sya/DSC03453.jpg',
        '/images/Hazim-Sya/DSC03456.jpg',
        '/images/Hazim-Sya/DSC03527.jpg',
        '/images/Hazim-Sya/DSC03539.jpg',
        '/images/Hazim-Sya/DSC03567.jpg',
        '/images/Hazim-Sya/DSC03585.jpg',
        '/images/Hazim-Sya/DSC03598.jpg',
        '/images/Hazim-Sya/DSC03612.jpg',
        '/images/Hazim-Sya/DSC03616.jpg',
        '/images/Hazim-Sya/DSC03494.jpg',
      ],
    },
    {
      name: 'Hazim & Sya',
      images: '/images/DSC03574.jpg',
      desc: "Congratulations to Hazim and Sya on their special day! 🎉 May your love continue to grow stronger with each passing day, and may your journey together be filled with laughter, love, and endless joy. Here's to a lifetime of happiness and beautiful moments together. Cheers to the newlyweds! ",
      slug: 'hazim-sya',
      moreImages: [
        '/images/Hazim-Sya/DSC02934.jpg',
        '/images/Hazim-Sya/DSC02987.jpg',
        '/images/Hazim-Sya/DSC03066.jpg',
        '/images/Hazim-Sya/DSC03425.jpg',
        '/images/Hazim-Sya/DSC03443.jpg',
        '/images/Hazim-Sya/DSC03453.jpg',
        '/images/Hazim-Sya/DSC03456.jpg',
        '/images/Hazim-Sya/DSC03527.jpg',
        '/images/Hazim-Sya/DSC03539.jpg',
        '/images/Hazim-Sya/DSC03567.jpg',
        '/images/Hazim-Sya/DSC03585.jpg',
        '/images/Hazim-Sya/DSC03598.jpg',
        '/images/Hazim-Sya/DSC03612.jpg',
        '/images/Hazim-Sya/DSC03616.jpg',
        '/images/Hazim-Sya/DSC03494.jpg',
      ],
    },
    {
      name: 'Priti & Priam',
      images: '/images/DSC_7505.jpg',
      slug: 'priti-priam',
      desc: "Congratulations to Hazim and Sya on their special day! 🎉 May your love continue to grow stronger with each passing day, and may your journey together be filled with laughter, love, and endless joy. Here's to a lifetime of happiness and beautiful moments together. Cheers to the newlyweds! ",
      moreImages: [
        '/images/Hazim-Sya/DSC02934.jpg',
        '/images/Hazim-Sya/DSC02987.jpg',
        '/images/Hazim-Sya/DSC03066.jpg',
        '/images/Hazim-Sya/DSC03425.jpg',
        '/images/Hazim-Sya/DSC03443.jpg',
        '/images/Hazim-Sya/DSC03453.jpg',
        '/images/Hazim-Sya/DSC03456.jpg',
        '/images/Hazim-Sya/DSC03527.jpg',
        '/images/Hazim-Sya/DSC03539.jpg',
        '/images/Hazim-Sya/DSC03567.jpg',
        '/images/Hazim-Sya/DSC03585.jpg',
        '/images/Hazim-Sya/DSC03598.jpg',
        '/images/Hazim-Sya/DSC03612.jpg',
        '/images/Hazim-Sya/DSC03616.jpg',
        '/images/Hazim-Sya/DSC03494.jpg',
      ],
    },
  ],

  blogDetails: [
    {
      title:
        "Susah nak 'close' client? Ini 5 tips tingkat kadar jualan sebagai freelancers",
      desc: "Ketahui apa itu 'sales' dan tingkatkan kadar 'closing'",
      authorImage: '',
      author: 'Afiq Sam',
      date: '26/10/2023',
      coverImage: '/images/img1.jpg',
      creditImage: '',
    },
    {
      title: 'Nak berhenti kerja? Ketahui 7 perkara ini dahuluu',
      desc: '7 perkara penting perlu tahu sebelum berhenti kerja dan freelance sepenuh masa',
      authorImage: '',
      author: 'Afiq Sam',
      date: '30/06/2023',
      coverImage: '/images/img2.jpg',
      creditImage: '',
    },
    {
      title: 'Pengorbanan seorang freelancerr',
      desc: 'Pengorbanan seorang freelancer',
      authorImage: '',
      author: 'Afiq Sam',
      date: '15/04/2023',
      coverImage: '/images/img3.jpg',
      creditImage: '',
    },
    {
      title: 'Nak berhenti kerja? Ketahui 7 perkara ini dahulu',
      desc: '7 perkara penting perlu tahu sebelum berhenti kerja dan freelance sepenuh masa',
      authorImage: '',
      author: 'Afiq Sam',
      date: '3/02/2023',
      coverImage: '/images/img4.jpg',
      creditImage: '',
    },
    {
      title:
        "Susah nak 'close' client? Ini 5 tips tingkat kadar jualan sebagai freelancer",
      desc: "Ketahui apa itu 'sales' dan tingkatkan kadar 'closing'",
      authorImage: '',
      author: 'Afiq Sam',
      date: '26/10/2023',
      coverImage: '/images/img1.jpg',
      creditImage: '',
    },
    {
      title: 'Nak berhenti kerja? Ketahui 7 perkara ini dahulur',
      desc: '7 perkara penting perlu tahu sebelum berhenti kerja dan freelance sepenuh masa',
      authorImage: '',
      author: 'Afiq Sam',
      date: '30/06/2023',
      coverImage: '/images/img2.jpg',
      creditImage: '',
    },
    {
      title: 'Pengorbanan seorang freelancer',
      desc: 'Pengorbanan seorang freelancer',
      authorImage: '',
      author: 'Afiq Sam',
      date: '15/04/2023',
      coverImage: '/images/img3.jpg',
      creditImage: '',
    },
    {
      title: 'Nak berhenti kerja? Ketahui 7 perkara ini dahuluz',
      desc: '7 perkara penting perlu tahu sebelum berhenti kerja dan freelance sepenuh masa',
      authorImage: '',
      author: 'Afiq Sam',
      date: '3/02/2023',
      coverImage: '/images/img4.jpg',
      creditImage: '',
    },
  ],
};

export default data;
